# Generated by Django 5.1.2 on 2024-10-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ngodatamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngoname', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('unique_id', models.UUIDField()),
                ('admin_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ngodatatable',
            },
        ),
    ]
